config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  get "pages/home", to: "pages#home"

  resources :uploads, only: %i[new create]
  resources :rulesets, only: %i[index create]
  resource :government_ruleset, only: %i[show create]
  resource :security_ruleset, only: %i[show create]
  resources :rules, only: %i[show index]

  scope via: :all do
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unprocessable_entity"
    get "/429", to: "errors#too_many_requests"
    get "/500", to: "errors#internal_server_error"
  end
end

app/controllers/security_ruleset_controller.rb
class SecurityRulesetController < ApplicationController
  include RulesetValidations

  before_action :validate_file_upload!, only: [:create]
  before_action :clear_errors

  def new
  end

  def create
    crunch_hash = JSON.parse(crunch42_data)
    @score = crunch_hash['score']
    @openapi = crunch_hash['openapiState']
    @counter = crunch_hash['issueCounter']
    @criticality = crunch_hash['criticality']
    @issues = crunch_hash['data']['issues'].map do |issue|
      lines = issue[1]['issues'].pluck('pointer')
      [issue[1]['criticality'],issue[1]['description'], lines]
    end

    render 'show'
  end

  private

  def crunch42_data
    return File.read('fakecrunchresults.json') if ENV['BYPASS_API'] == 'true'

    Linters::CrunchApi.new(file: ruleset_params[:oas_file]).lint_to_json
  end

  def ruleset_params
    params.permit(:oas_file)
  end

  def clear_errors
    flash[:error] = nil
  end
end

app/controllers/security_rulesets_controller.rb
# frozen_string_literal: true

class SecurityRulesetsController < ApplicationController

  def show
    @breadcrumbs = { Home: root_path, Uploads: new_upload_path, Rulesets: rulesets_path, Report:"#"}
    upload = Upload.find(session[:upload_id])
    return redirect_to root_path, alert: "Please re upload your file" if upload.nil?

    crunch_hash = JSON.parse(crunch42_data(upload))
    @score = crunch_hash["score"]
    @openapi = crunch_hash["openapiState"]
    @counter = crunch_hash["issueCounter"]
    @criticality = crunch_hash["criticality"]
    @issues =
      crunch_hash["data"]["issues"].map do |_key, issue|
        lines = issue["issues"].pluck("pointer").sort
        [issue["criticality"].to_i, issue["description"], lines]
      end
      @issues = @issues.sort_by{|s| -s[0]}
  end

  private

  def crunch42_data(upload)
    return File.read("fakecrunchresults.json") if ENV["BYPASS_API"] == "true"

    Tempfile.open(upload.oas_file.key) do |oas_file|
      content = upload.oas_file.download.encode('utf-8', 'binary', invalid: :replace, undef: :replace)
      oas_file.write content
      oas_file.rewind
      Linters::CrunchApi::Fetch.new(file: oas_file).lint_to_json
    end
  end

  def ruleset_params
    params.permit(:oas_file)
  end
end

app/views/security_ruleset/_form.html.erb
<div class="govuk-grid-column-two-thirds">

  <div class="govuk-form-group">
    <label class="govuk-label" for="file-upload-1">
      Upload an OpenAPI document
    </label>
    <%= form_tag(security_ruleset_index_path, method: :post, multipart: true) do %>
      <%= file_field_tag "oas_file", class: "govuk-file-upload", label: { text: "Upload an OpenAPI document" }, id: "oas_file", name: "oas_file" %>
      <br>
      <br>
      <%= hidden_field_tag "ruleset_name", @ruleset_name %>
      <%= submit_tag "Submit", class: "govuk-button", data: {module: "govuk-button" } %>
    <% end %>
  </div>
  <%# this is a temp error solution just so we can get some kind of feedback for now %>
  <% if flash[:error] %>
    <div class="govuk-error-message">
      <%= flash[:error] %>
    </div>
  <% end %>
</div>