config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  get "pages/home", to: "pages#home"

  resources :uploads, only: %i[new create]
  resources :rulesets, only: %i[index create]
  resource :government_ruleset, only: %i[show create]
  resource :security_ruleset, only: %i[show create]
  resources :rules, only: %i[show index]

  scope via: :all do
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unprocessable_entity"
    get "/429", to: "errors#too_many_requests"
    get "/500", to: "errors#internal_server_error"
  end
end

app/controllers/rulesets_controller.rb
# frozen_string_literal: true

# TODO: Separate this out into a controller per ruleset
class RulesetsController < ApplicationController
  before_action :set_ruleset_name, only: %i[create]
  before_action :clear_errors

  def index
    @breadcrumbs = { Home: root_path, Uploads: new_upload_path, Rulesets: rulesets_path}
  end

  def create
    return redirect_to "/security_ruleset" if @ruleset_name == "security_ruleset"

    redirect_to government_ruleset_path(ruleset_name: @ruleset_name)
  end

  private

  def set_ruleset_name
    @ruleset_name = ruleset_params[:ruleset_name]
  end

  def ruleset_params
    params.permit(:ruleset_name)
  end

  def clear_errors
    flash[:error] = nil
  end
end

app/views/ruleset/_form.html.erb
<div class="govuk-grid-column-two-thirds">

  <div class="govuk-form-group">
    <label class="govuk-label" for="file-upload-1">
      Upload an OpenAPI document
    </label>
    <%= form_tag("/ruleset", method: :post, multipart: true) do %>
      <%= file_field_tag "oas_file", class: "govuk-file-upload", label: { text: "Upload an OpenAPI document" }, id: "oas_file", name: "oas_file" %>
      <br>
      <br>
      <%= hidden_field_tag "ruleset_name", @ruleset_name %>
      <%= submit_tag "Submit", class: "govuk-button", data: {module: "govuk-button" } %>
    <% end %>
  </div>
  <%# this is a temp error solution just so we can get some kind of feedback for now %>
  <% if flash[:error] %>
    <div class="govuk-error-message">
      <%= flash[:error] %>
    </div>
  <% end %>
</div>

app/views/ruleset/index.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">GOV.UK OpenAPI Linting Service</h1>

    <%= form_tag(ruleset_index_path, method: :post) do %>
      <div class="govuk-form-group" name="which-linter">
        <fieldset class="govuk-fieldset">
          <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
            <h1 class="govuk-fieldset__heading">
              Which ruleset would you like to test your OpenAPI document against?
            </h1>
          </legend>
          <div class="govuk-radios" data-module="govuk-radios">
            <div class="govuk-radios__item">
              <%= text_field_tag("ruleset_name", "security_ruleset", class: "govuk-radios__input", type: "radio", name: "ruleset_name" ) %>
              <%= label_tag("security_ruleset", "Security ruleset", class: "govuk-label govuk-radios__label", for: "security-ruleset") %>
            </div>
            <div class="govuk-radios__item">
              <%= text_field_tag("ruleset_name", "government_ruleset", class: "govuk-radios__input", type: "radio", name: "ruleset_name") %>
              <%= label_tag("gov-ruleset", "UK government ruleset", class: "govuk-label govuk-radios__label", for: "gov-ruleset") %>
            </div>
          </div>
        </fieldset>
      </div>

      <%= submit_tag("Continue", class: "govuk-button", data: { module: "govuk-button" }) %>
    <% end %>

  </div>
</div>