config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  get "pages/home", to: "pages#home"

  resources :uploads, only: %i[new create]
  resources :rulesets, only: %i[index create]
  resource :government_ruleset, only: %i[show create]
  resource :security_ruleset, only: %i[show create]
  resources :rules, only: %i[show index]

  scope via: :all do
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unprocessable_entity"
    get "/429", to: "errors#too_many_requests"
    get "/500", to: "errors#internal_server_error"
  end
end

app/models/upload.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: uploads
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Upload < ApplicationRecord
  include ActiveModel::Validations
  # Sets the maximum file size allowed as a constant
  # If no value is specified in the environment variables we
  # fall back to 100mb as a hard-coded safety limit
  # Note: The web server configuration may enforce a lower limit
  MAX_FILE_SIZE = Integer(ENV["MAX_FILE_SIZE"] || 100_000)

  has_one_attached :oas_file

  validates :oas_file,
            presence: {
              message: "No file was selected"
            },
            file_size: {
              less_than_or_equal_to: MAX_FILE_SIZE.kilobytes,
              message: "Your file exceeds the maximum size of #{MAX_FILE_SIZE} kilobytes"
            },
            file_content_type: {
              allow: ["application/json"],
              message: "This is not a valid JSON file"
            }
end

app/controllers/uploads_controller.rb
# frozen_string_literal: true

class UploadsController < ApplicationController
  def new
    @breadcrumbs = { Home: root_path, Uploads: new_upload_path}
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(
      oas_file: file_params[:oas_file]
    )

    # Save this to the database once we find out if we can use the database
    # For now we can store the info in the session
    if @upload.save
      session[:upload_id] = @upload.id
      redirect_to :rulesets
    else
      render "new"
    end
  end

  private

  def file_params
    params.permit(:oas_file)
  end
end

app/views/uploads/index.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">Check your OpenAPI documents for security issues</h1>
  </div>
  <div class="govuk-grid-column-full">

      <div class="govuk-grid-column-two-thirds">

        <div class="govuk-form-group <%= 'govuk-form-group--error' if flash[:error] %>">
          <label class="govuk-label" for="file-upload-1">
            Upload an OpenAPI document
          </label>
          <p id="file-upload-1-error" class="govuk-error-message">
            <span class="govuk-visually-hidden">Error:</span> <%= flash[:error] %>
          </p>
          <%= form_tag(uploads_path, method: :post, multipart: true) do %>
            <%= file_field_tag "oas_file", class: "govuk-file-upload", label: { text: flash[:error] }, id: "oas_file", name: "oas_file",  accept: "application/json" %>
            <br>
            <br>
            <%= hidden_field_tag "ruleset_name", @ruleset_name %>
            <%= submit_tag "Submit", class: "govuk-button", data: {module: "govuk-button" } %>
          <% end %>
        </div>

      </div>

  </div>
</div>

app/views/uploads/new.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">Upload your OpenAPI specification</h1>
  </div>
  <div class="govuk-grid-column-full">

      <div class="govuk-grid-column-two-thirds">

        <div class="govuk-form-group <%= 'govuk-form-group--error' unless @upload.errors.empty? %>">
          <label class="govuk-label" for="file-upload-1">
            Upload your JSON file. It must conform with the OpenAPI standard.
          </label>
          <%= form_for(@upload, method: :post, multipart: true) do %>
            <p id="file-upload-1-error" class="govuk-error-message">
              <% @upload.errors.each do |error| %>
                <span class="govuk-visually-hidden">Error:</span> <%= error.message %>
              <% end %>
            </p>
            <%= file_field_tag "oas_file", class: "govuk-file-upload", id: "oas_file", name: "oas_file",  accept: "application/json" %>
            <br>
            <br>
            <%= hidden_field_tag "ruleset_name", @ruleset_name %>
            <%= submit_tag "Submit", class: "govuk-button", data: {module: "govuk-button" } %>
          <% end %>
        </div>
      </div>
  </div>
</div>